// Runs in the real native WebView, with deterministic transport faults only.
// The host also runs separate real-model, clipboard and native-dialog checks.
window.chatChecksDone = false;
window.chatChecksError = null;
(async () => {
  const originalAPI = api, originalConfirm = window.confirm;
  const assert = (ok, detail) => { if (!ok) throw new Error(detail); };
  const tick = () => new Promise(resolve => setTimeout(resolve, 90));
  const idle = async () => { for (let i=0; i<200 && controller; i++) await tick(); assert(!controller, 'request completed'); };
  const key = options => { const event = new KeyboardEvent('keydown', {key:'Enter', bubbles:true, cancelable:true, ...options}); $('prompt').dispatchEvent(event); return event.defaultPrevented; };
  const input = text => { $('prompt').value = text; $('prompt').dispatchEvent(new Event('input')); };
  let stream, calls = [], fail = false;
  const emit = item => stream.enqueue(new TextEncoder().encode(JSON.stringify(item) + '\n'));
  const finish = limited => { emit({done:true, limited, eval_count:32, eval_duration:1e9}); stream.close(); };
  try {
    // Locale resolution does not depend on the developer or CI machine's language.
    for (const locale of ['de', 'de-DE', 'de_AT.UTF-8', 'DE-ch', 'de@euro']) assert(resolveLanguage('system', locale) === 'de', `German system locale: ${locale}`);
    for (const locale of ['en-US', 'fr-FR', 'debug', '', undefined]) assert(resolveLanguage('system', locale) === 'en', `English fallback: ${locale}`);
    assert(resolveLanguage('en', 'de-DE') === 'en' && resolveLanguage('de', 'en-US') === 'de', 'manual preference overrides OS');
    assert(resolveLanguage('invalid', 'de-DE') === 'de', 'invalid preference returns to system');
    const international = new Set(['Geist', 'geist', 'English', 'Deutsch', 'Home Assistant', 'Terminal', 'VS Code · Continue', '—', '— tok/s', '— RAM']);
    const sources = [...staticTexts.map(([, text]) => text.trim()), ...staticAttributes.map(([, , text]) => text)];
    const missing = [...new Set(sources.filter(text => !international.has(text) && !Object.hasOwn(german, text)))];
    assert(!missing.length, `Missing German interface translations: ${missing.join(' | ')}`);
    assert($('new-chat').querySelector('svg') && !$('new-chat').textContent.trim(), 'clear test uses a labelled trash icon');
    assert($('new-chat').getAttribute('aria-label') === t('Clear test'), 'trash accessible label follows locale');
    assert($('test-speed').closest('.model-metrics') && $('test-size').closest('.model-metrics'), 'speed and model size live in the model header');
    assert(new Set([...document.querySelectorAll('[id]')].map(el => el.id)).size === document.querySelectorAll('[id]').length, 'unique IDs preserve control bindings');
    api = async (path, body, signal) => {
      if (path !== '/app/generate') return originalAPI(path, body, signal);
      calls.push(body);
      if (fail) throw new Error("The prompt does not fit this model's context. Try a shorter text.");
      return new Response(new ReadableStream({start(c) { stream=c; signal.addEventListener('abort', () => c.error(new DOMException('Stopped','AbortError')), {once:true}); }}));
    };
    const ring = document.createElement('span'); ring.className='model-ring';
    const downloadModel = {...state.models[0], installed:false, partial:0};
    renderRing(ring, downloadModel, {phase:'', job_model:''});
    assert(ring.dataset.stage === 'missing' && ring.getAttribute('role') === 'img', 'missing download is an empty, labelled ring');
    renderRing(ring, downloadModel, {phase:'downloading', job_model:downloadModel.id, received:downloadModel.bytes / 2});
    assert(ring.dataset.stage === 'downloading' && ring.getAttribute('aria-valuenow') === '50' && ring.style.getPropertyValue('--ring-progress') === '50', 'download ring exposes real 50 percent progress');
    renderRing(ring, {...downloadModel, partial:downloadModel.bytes / 4}, {phase:'',job_model:''});
    assert(ring.dataset.stage === 'paused' && ring.getAttribute('aria-valuenow') === '25', 'paused download retains progress');
    renderRing(ring, downloadModel, {phase:'verifying', job_model:downloadModel.id, received:downloadModel.bytes});
    assert(ring.dataset.stage === 'verifying' && !ring.hasAttribute('aria-valuenow'), '100 percent transfer does not imply a verified completed download');
    renderRing(ring, {...downloadModel, installed:true}, {phase:'',job_model:''});
    assert(ring.dataset.stage === 'downloaded' && ring.style.getPropertyValue('--ring-progress') === '100' && !ring.hasAttribute('aria-valuenow'), 'complete download closes the ring independent of active model');
    renderRing(ring, downloadModel, {phase:'',job_model:''});
    assert(ring.dataset.stage === 'missing' && ring.style.getPropertyValue('--ring-progress') === '0', 'removed or failed download clears completed state');
    showPage('models-page');
    assert(!$('models-page').hidden && !$('test-page').hidden && !document.querySelector('nav [data-page="test-page"]'), 'models and quick test share one view');
    assert([...document.querySelectorAll('.model .model-ring')].length === state.models.length, 'each model exposes download state before its name');
    assert(document.documentElement.scrollWidth <= innerWidth, 'model picker fits a small or zoomed window');
    assert($('model-chooser').tagName === 'SECTION', 'model list is visible without a disclosure');
    const panes = [$('models-page').querySelector('.model-sidebar').getBoundingClientRect(), $('test-page').getBoundingClientRect()];
    assert(innerWidth < 700 ? panes[0].bottom <= panes[1].top : panes[0].right <= panes[1].left, 'panes stack on small windows and sit side by side on wide ones');
    const activeID = state.active_id, alternative = state.models.find(m => m.id !== activeID && m.resource_fit !== 2);
    if (alternative) {
      input('Draft survives model selection'); choose(alternative.id);
      assert(manualChoice === alternative.id && !$('setup').hidden && state.active_id === activeID && document.activeElement === $('setup-start'), 'choosing a row prepares explicit setup; it neither downloads nor switches the daemon');
      choose(activeID);
      assert(!$('workspace').hidden && $('prompt').value === 'Draft survives model selection', 'return to the current model retains the draft');
      input('');
    }
    assert(window.geistNavigate('invalid') === false && !$('models-page').hidden, 'native routing is allowlisted');
    showPage('test-page');
    const sample = document.createElement('div'); sample.className = 'message-text markdown';
    $('result').hidden = false; $('result').append(sample);
    const markdown = '# Clear heading\n\nA **strong** and *gentle* paragraph &amp; text.\n\n## Details\n\n- One\n  - Nested\n- Two\n\n3. Third\n4. Fourth\n\n- [x] Done\n- [ ] Pending\n\n> A quote\n\n---\n\nInline `x < 2` and ~~old~~.\n\n```js\nconst text = "<script>unsafe</script>";\n' + 'x'.repeat(1600) + '\n```\n\n| Name | Value |\n| :--- | ---: |\n| Alpha | **42** |\n\n[Example](https://example.com/a?q=1&b=2)\n\n![remote](https://example.com/image.png)\n\n<script>window.markdownXSS = true</script>\n<img src=x onerror="window.markdownXSS=true">\n\n[bad](javascript:alert(1)) [file](file:///tmp/test) [data](data:text/html,evil) [credentials](https://u:p@example.com)';
    chatMarkdown.render(sample, markdown);
    assert(sample.querySelector('h3')?.textContent === 'Clear heading' && sample.querySelector('h4')?.textContent === 'Details', 'semantic Markdown headings');
    assert(sample.querySelectorAll('strong').length === 2 && sample.querySelector('em') && sample.querySelector('del'), 'inline formatting');
    assert(sample.querySelector('ul ul') && sample.querySelector('ol').start === 3 && sample.querySelectorAll('.task-check').length === 2, 'nested, numbered and task lists');
    assert(sample.querySelector('blockquote') && sample.querySelector('hr') && sample.textContent.includes('paragraph & text'), 'quotes, separator and entities');
    assert(sample.querySelector('pre code').textContent.includes('<script>unsafe</script>') && sample.querySelector('table th').scope === 'col', 'code and accessible table');
    assert(!sample.querySelector('script,img,iframe,object,a,style,input') && !window.markdownXSS, 'model HTML and URLs cannot execute, navigate or fetch');
    assert(sample.querySelectorAll('.reference-address').length === 2, 'only safe HTTP(S) addresses are offered for copying');
    const pre = sample.querySelector('pre'), codeCopy = sample.querySelector('.code-toolbar button');
    assert(pre.scrollWidth > pre.clientWidth && document.documentElement.scrollWidth <= innerWidth, 'long code scrolls inside its block');
    assert(codeCopy._markdownCopyText === pre.textContent, 'code copy retains literal contents');
    const literalCode = pre.textContent;
    $('ui-language').value='de'; $('ui-language').dispatchEvent(new Event('change')); await tick();
    assert(codeCopy.title === 'Code kopieren' && codeCopy.ariaLabel === 'Code kopieren' && sample.querySelector('.table-scroll').ariaLabel === 'Tabelle', 'existing Markdown icon labels switch language');
    assert(sample.querySelector('.task-check').ariaLabel === 'Abgehakt' && [...sample.querySelectorAll('.markdown-reference')].some(node => node.textContent.includes('Bild: remote')), 'Markdown wrapper labels switch without translating generated content');
    assert(pre.textContent === literalCode && sample.querySelector('pre') === pre, 'locale changes preserve literal code and DOM nodes');
    $('ui-language').value='en'; $('ui-language').dispatchEvent(new Event('change')); await tick();
    pre.scrollLeft = 45; codeCopy.focus();
    const heading = sample.firstChild;
    chatMarkdown.render(sample, markdown + '\n\nA final paragraph.');
    assert(sample.firstChild === heading && sample.querySelector('pre') === pre && pre.scrollLeft === 45 && document.activeElement === codeCopy, 'unchanged blocks preserve nodes, scroll and focus');
    chatMarkdown.render(sample, '```txt\nfirst');
    chatMarkdown.render(sample, '```txt\nfirst second\n```');
    assert(sample.querySelector('pre code').textContent === 'first second' && sample.querySelector('button')._markdownCopyText === 'first second', 'unfinished fence and streamed copy are updated');
    const malformed = '> '.repeat(80) + 'deep but preserved';
    chatMarkdown.render(sample, malformed);
    assert(sample.textContent.includes('deep but preserved'), 'deep input remains readable');
    sample.remove(); $('result').hidden = true;
    showPage('test-page'); assert(document.activeElement === $('prompt'), 'entering chat focuses composer');
    $('chat-help').querySelector('summary').focus(); render(state);
    assert(document.activeElement === $('chat-help').querySelector('summary'), 'status poll never steals focus');
    assert(!document.querySelector('[data-task]'), 'task presets removed');
    assert($('run').getAttribute('aria-label') === t('Send message'), 'send has an accessible name');
    input(''); assert($('run').disabled, 'empty send disabled');
    input('  \n  '); key(); assert(calls.length === 0, 'whitespace not submitted');
    const long = 'Very long draft line with umlauts äöü\n'.repeat(200) + 'x'.repeat(1800);
    input(long); assert($('prompt').value === long, 'long pasted text preserved');
    assert($('prompt').scrollHeight > $('prompt').clientHeight, 'long draft scrollable');
    assert($('run').getBoundingClientRect().bottom <= innerHeight, 'send visible with long draft');
    assert(document.documentElement.scrollWidth <= innerWidth, 'draft does not overflow horizontally');
    input('Remember lighthouse.');
    assert(!key({shiftKey:true}) && !key({isComposing:true}) && !key({keyCode:229}), 'newline and IME not intercepted');
    $('prompt').dispatchEvent(new CompositionEvent('compositionstart'));
    key(); assert(calls.length === 0, 'composition fallback not sent');
    $('prompt').dispatchEvent(new CompositionEvent('compositionend'));
    key({repeat:true}); assert(calls.length === 0, 'held Enter not sent');
    key(); assert(calls.length === 1 && $('prompt').value === '', 'Enter sends once and clears submitted draft');
    input('My next draft'); key(); assert(calls.length === 1 && $('prompt').value === 'My next draft', 'no duplicate during generation; next draft preserved');
    showPage('connect-page'); showPage('test-page');
    assert(!$('test-page').hidden && controller && $('prompt').value === 'My next draft', 'returning to a running quick test preserves the draft and keeps Stop reachable');
    await tick();
    const answer = 'A complete visible line.\n'.repeat(90) + '<script>never executed</script>' + 'z'.repeat(1400);
    emit({response:answer}); await tick();
    assert($('output').markdownSource === answer && $('output').textContent.includes('z'.repeat(1400)) && !$('output').querySelector('script'), 'full safe Markdown rendering');
    assert($('transcript').scrollHeight > $('transcript').clientHeight, 'history scrollable');
    assert(document.documentElement.scrollWidth <= innerWidth, 'long reply wraps');
    $('transcript').scrollTop = 0; $('transcript').dispatchEvent(new Event('scroll'));
    const firstText = $('output').querySelector('p').firstChild;
    const selection = window.getSelection(), range = document.createRange();
    range.setStart(firstText, 0); range.setEnd(firstText, 10); selection.removeAllRanges(); selection.addRange(range);
    const selectedText = selection.toString();
    emit({response:'\nLast line.'}); await tick();
    assert(selection.toString() === selectedText, 'streaming does not destroy a text selection');
    selection.removeAllRanges(); await tick();
    assert($('transcript').scrollTop === 0 && !$('latest').hidden, 'reading older text is not interrupted');
    $('latest').click(); assert($('latest').hidden && $('transcript').scrollTop > 0, 'latest returns to bottom');
    finish(false); await idle();
    assert(conversation.length === 2 && conversation[1].content === answer+'\nLast line.', 'full reply kept in session context');
    assert($('prompt').value === 'My next draft', 'generation does not overwrite next draft');
    assert(lastReply.tokens === 32 && lastReply.rate === 32 && $('chat-speed').textContent === rateText(32), 'speed uses backend tokens, not streamed chunks');
    assert(document.querySelector('.reply-metrics').textContent.includes('32'), 'completed reply retains its own metrics');
    const untranslatedAnswer = $('output').markdownSource;
    uiText($('connection-result'), 'Copied. The configuration contains your private local key.');
    $('ui-language').value='de'; $('ui-language').dispatchEvent(new Event('change')); await tick();
    assert(document.documentElement.lang === 'de' && $('new-chat').title === 'Test leeren', 'language switch updates document and icon tooltips');
    assert(rateText(32.5) === '32,5 Token/s' && bytes(1500000000) === '1,50 GB', 'German numbers and units');
    assert($('connection-result').textContent === t('Copied. The configuration contains your private local key.'), 'existing interface statuses switch language');
    assert($('output').markdownSource === untranslatedAnswer && $('prompt').value === 'My next draft', 'language change leaves answer and draft untouched');
    $('ui-language').value='en'; $('ui-language').dispatchEvent(new Event('change')); await tick();
    assert(rateText(32.5) === '32.5 tok/s' && $('new-chat').title === 'Clear test', 'switching back restores English');
    const measuredReply = lastReply;
    const savedState = state;
    state = {...savedState, resources:{scope:'geistd', rss_bytes:2**30, cpu_percent:0}}; renderPerformance();
    assert($('chat-memory').textContent === '1.0 GiB RAM' && $('performance-cpu').textContent === '0.0 %', 'real zero CPU differs from unknown');
    state = {...savedState, resources:{scope:'geistd', rss_bytes:null, cpu_percent:null}}; renderPerformance();
    assert($('chat-memory').textContent === '— RAM' && $('performance-cpu').textContent === '—', 'unknown resource counters are not zero');
    state = {...savedState, hardware:{...savedState.hardware, known:false, ram:0}}; renderPerformance();
    assert($('performance-ram').textContent === '—', 'failed system memory read is unknown, not zero');
    state = {...savedState, active:'another model'}; renderPerformance();
    assert(lastReply === null && $('performance-tokens').textContent === '—', 'model change invalidates last reply metrics');
    state = savedState; lastReply = measuredReply; renderPerformance();
    input('Which word?'); key(); await tick();
    assert(calls[1].messages.length === 3 && calls[1].messages[1].content === conversation[1].content, 'follow-up includes history without truncation');
    emit({response:'Lighthouse.'}); finish(true); await idle();
    assert($('result').querySelectorAll('article').length === 4 && $ ('result').querySelector('.assistant .markdown').markdownSource === answer+'\nLast line.', 'earlier messages retained');
    assert($('result').textContent.includes(t('Continue response')), 'token limit has explicit continuation');
    input('Draft to keep during continuation');
    const more = [...$('result').querySelectorAll('button')].find(button => button.dataset.label === 'Continue response');
    more.click(); await tick();
    assert($('prompt').value === 'Draft to keep during continuation', 'continuation preserves the next draft');
    emit({response:'More detail.'}); finish(false); await idle();
    fail = true; input('Follow-up that does not fit'); key(); await idle();
    assert(conversation.length === 6 && $('prompt').value === 'Follow-up that does not fit', 'rejected request retains draft and previous context');
    assert($('result').textContent.includes(t('This test does not fit the model’s context. Shorten your draft or use Clear test to start again. No earlier messages have been removed.')), 'context limit explained');
    fail = false; input('A response to stop'); key(); await tick(); emit({response:'Partial response'}); await tick(); $('stop').click(); await idle();
    assert(conversation.at(-1).content === 'Partial response' && $('result').textContent.includes(t('Stopped. Partial output is kept here.')), 'stop preserves marked partial response');
    assert(document.activeElement === $('prompt'), 'stopping returns focus to composer');
    assert(lastReply === null && $('chat-speed').textContent === rateText(null), 'aborted reply never reports final generation speed');
    window.confirm = () => false; $('new-chat').click(); assert(conversation.length === 8, 'cancel new chat keeps text');
    window.confirm = () => true; $('new-chat').click(); assert(conversation.length === 0 && !$('chat-empty').hidden && !$('prompt').value, 'new chat clears only this session');
    await tick();
    const empty = $('chat-empty').querySelector('h3').getBoundingClientRect(), transcript = $('transcript').getBoundingClientRect();
    assert(empty.top >= transcript.top && empty.bottom <= transcript.bottom, `empty-state label is fully visible: ${JSON.stringify({empty:empty.toJSON(), transcript:transcript.toJSON(), scroll:$('transcript').scrollTop})}`);
    $('chat-help').open = true;
    const help = document.querySelector('.help-content').getBoundingClientRect();
    assert(help.top >= 0 && help.bottom <= innerHeight && help.left >= 0 && help.right <= innerWidth, 'help readable inside window');
    document.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape', bubbles:true, cancelable:true}));
    assert(!$('chat-help').open && document.activeElement === $('chat-help').querySelector('summary'), 'Escape closes help and returns focus');
    $('chat-help').open = true;
    $('prompt').dispatchEvent(new Event('pointerdown', {bubbles:true}));
    assert(!$('chat-help').open, 'outside click dismisses help');
    showPage('models-page'); $('performance').open = true; await tick();
    const panel = document.querySelector('.performance-content');
    panel.focus(); panel.scrollTop=panel.scrollHeight;
    assert(panel.scrollTop > 0 && panel.scrollHeight > panel.clientHeight, 'performance details scroll within the model manager');
    assert(document.documentElement.scrollWidth <= innerWidth, 'performance manager does not clip horizontally');
    document.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape', bubbles:true, cancelable:true}));
    assert(!$('performance').open && document.activeElement === $('performance').querySelector('summary'), 'performance Escape returns focus');
    showPage('test-page');
    $('prompt').focus();
    const computed = getComputedStyle(document.body);
    assert(computed.backgroundColor === 'rgb(255, 255, 255)', 'white background is consistent across system appearances');
    window.chatChecksDone = true;
  } catch (error) { window.chatChecksError = error.message; }
  finally { api = originalAPI; window.confirm = originalConfirm; }
})();
true;
