// Runs in the real native WebView, with deterministic transport faults only.
// The host also runs separate real-model, clipboard and native-dialog checks.
window.chatChecksDone = false;
window.chatChecksError = null;
(async () => {
  const originalAPI = api, originalConfirm = window.confirm;
  const assert = (ok, detail) => { if (!ok) throw new Error(detail); };
  const tick = () => new Promise(resolve => setTimeout(resolve, 90));
  const idle = async () => { for (let i=0; i<200 && controller; i++) await tick(); assert(!controller, 'request completed'); };
  const key = options => { const event = new KeyboardEvent('keydown', {key:'Enter', bubbles:true, cancelable:true, ...options}); $('prompt').dispatchEvent(event); return event.defaultPrevented; };
  const input = text => { $('prompt').value = text; $('prompt').dispatchEvent(new Event('input')); };
  let stream, calls = [], fail = false;
  const emit = item => stream.enqueue(new TextEncoder().encode(JSON.stringify(item) + '\n'));
  const finish = limited => { emit({done:true, limited, eval_count:32, eval_duration:1e9}); stream.close(); };
  try {
    api = async (path, body, signal) => {
      if (path !== '/app/generate') return originalAPI(path, body, signal);
      calls.push(body);
      if (fail) throw new Error("The prompt does not fit this model's context. Try a shorter text.");
      return new Response(new ReadableStream({start(c) { stream=c; signal.addEventListener('abort', () => c.error(new DOMException('Stopped','AbortError')), {once:true}); }}));
    };
    const sample = document.createElement('div'); sample.className = 'message-text markdown';
    $('result').hidden = false; $('result').append(sample);
    const markdown = '# Clear heading\n\nA **strong** and *gentle* paragraph &amp; text.\n\n## Details\n\n- One\n  - Nested\n- Two\n\n3. Third\n4. Fourth\n\n- [x] Done\n- [ ] Pending\n\n> A quote\n\n---\n\nInline `x < 2` and ~~old~~.\n\n```js\nconst text = "<script>unsafe</script>";\n' + 'x'.repeat(1600) + '\n```\n\n| Name | Value |\n| :--- | ---: |\n| Alpha | **42** |\n\n[Example](https://example.com/a?q=1&b=2)\n\n![remote](https://example.com/image.png)\n\n<script>window.markdownXSS = true</script>\n<img src=x onerror="window.markdownXSS=true">\n\n[bad](javascript:alert(1)) [file](file:///tmp/test) [data](data:text/html,evil) [credentials](https://u:p@example.com)';
    chatMarkdown.render(sample, markdown);
    assert(sample.querySelector('h3')?.textContent === 'Clear heading' && sample.querySelector('h4')?.textContent === 'Details', 'semantic Markdown headings');
    assert(sample.querySelectorAll('strong').length === 2 && sample.querySelector('em') && sample.querySelector('del'), 'inline formatting');
    assert(sample.querySelector('ul ul') && sample.querySelector('ol').start === 3 && sample.querySelectorAll('.task-check').length === 2, 'nested, numbered and task lists');
    assert(sample.querySelector('blockquote') && sample.querySelector('hr') && sample.textContent.includes('paragraph & text'), 'quotes, separator and entities');
    assert(sample.querySelector('pre code').textContent.includes('<script>unsafe</script>') && sample.querySelector('table th').scope === 'col', 'code and accessible table');
    assert(!sample.querySelector('script,img,iframe,object,a,style,input') && !window.markdownXSS, 'model HTML and URLs cannot execute, navigate or fetch');
    assert(sample.querySelectorAll('.reference-address').length === 2, 'only safe HTTP(S) addresses are offered for copying');
    const pre = sample.querySelector('pre'), codeCopy = sample.querySelector('.code-toolbar button');
    assert(pre.scrollWidth > pre.clientWidth && document.documentElement.scrollWidth <= innerWidth, 'long code scrolls inside its block');
    assert(codeCopy._markdownCopyText === pre.textContent, 'code copy retains literal contents');
    pre.scrollLeft = 45; codeCopy.focus();
    const heading = sample.firstChild;
    chatMarkdown.render(sample, markdown + '\n\nA final paragraph.');
    assert(sample.firstChild === heading && sample.querySelector('pre') === pre && pre.scrollLeft === 45 && document.activeElement === codeCopy, 'unchanged blocks preserve nodes, scroll and focus');
    chatMarkdown.render(sample, '```txt\nfirst');
    chatMarkdown.render(sample, '```txt\nfirst second\n```');
    assert(sample.querySelector('pre code').textContent === 'first second' && sample.querySelector('button')._markdownCopyText === 'first second', 'unfinished fence and streamed copy are updated');
    const malformed = '> '.repeat(80) + 'deep but preserved';
    chatMarkdown.render(sample, malformed);
    assert(sample.textContent.includes('deep but preserved'), 'deep input remains readable');
    sample.remove(); $('result').hidden = true;
    showPage('test-page'); assert(document.activeElement === $('prompt'), 'entering chat focuses composer');
    $('chat-help').querySelector('summary').focus(); render(state);
    assert(document.activeElement === $('chat-help').querySelector('summary'), 'status poll never steals focus');
    assert(!document.querySelector('[data-task]'), 'task presets removed');
    assert($('run').getAttribute('aria-label') === t('Send message'), 'send has an accessible name');
    input(''); assert($('run').disabled, 'empty send disabled');
    input('  \n  '); key(); assert(calls.length === 0, 'whitespace not submitted');
    const long = 'Very long draft line with umlauts äöü\n'.repeat(200) + 'x'.repeat(1800);
    input(long); assert($('prompt').value === long, 'long pasted text preserved');
    assert($('prompt').scrollHeight > $('prompt').clientHeight, 'long draft scrollable');
    assert($('run').getBoundingClientRect().bottom <= innerHeight, 'send visible with long draft');
    assert(document.documentElement.scrollWidth <= innerWidth, 'draft does not overflow horizontally');
    input('Remember lighthouse.');
    assert(!key({shiftKey:true}) && !key({isComposing:true}) && !key({keyCode:229}), 'newline and IME not intercepted');
    $('prompt').dispatchEvent(new CompositionEvent('compositionstart'));
    key(); assert(calls.length === 0, 'composition fallback not sent');
    $('prompt').dispatchEvent(new CompositionEvent('compositionend'));
    key({repeat:true}); assert(calls.length === 0, 'held Enter not sent');
    key(); assert(calls.length === 1 && $('prompt').value === '', 'Enter sends once and clears submitted draft');
    input('My next draft'); key(); assert(calls.length === 1 && $('prompt').value === 'My next draft', 'no duplicate during generation; next draft preserved');
    await tick();
    const answer = 'A complete visible line.\n'.repeat(90) + '<script>never executed</script>' + 'z'.repeat(1400);
    emit({response:answer}); await tick();
    assert($('output').markdownSource === answer && $('output').textContent.includes('z'.repeat(1400)) && !$('output').querySelector('script'), 'full safe Markdown rendering');
    assert($('transcript').scrollHeight > $('transcript').clientHeight, 'history scrollable');
    assert(document.documentElement.scrollWidth <= innerWidth, 'long reply wraps');
    $('transcript').scrollTop = 0; $('transcript').dispatchEvent(new Event('scroll'));
    const firstText = $('output').querySelector('p').firstChild;
    const selection = window.getSelection(), range = document.createRange();
    range.setStart(firstText, 0); range.setEnd(firstText, 10); selection.removeAllRanges(); selection.addRange(range);
    const selectedText = selection.toString();
    emit({response:'\nLast line.'}); await tick();
    assert(selection.toString() === selectedText, 'streaming does not destroy a text selection');
    selection.removeAllRanges(); await tick();
    assert($('transcript').scrollTop === 0 && !$('latest').hidden, 'reading older text is not interrupted');
    $('latest').click(); assert($('latest').hidden && $('transcript').scrollTop > 0, 'latest returns to bottom');
    finish(false); await idle();
    assert(conversation.length === 2 && conversation[1].content === answer+'\nLast line.', 'full reply kept in session context');
    assert($('prompt').value === 'My next draft', 'generation does not overwrite next draft');
    assert(lastReply.tokens === 32 && lastReply.rate === 32 && $('chat-speed').textContent === rateText(32), 'speed uses backend tokens, not streamed chunks');
    assert(document.querySelector('.reply-metrics').textContent.includes('32'), 'completed reply retains its own metrics');
    const measuredReply = lastReply;
    const savedState = state;
    state = {...savedState, resources:{scope:'geistd', rss_bytes:2**30, cpu_percent:0}}; renderPerformance();
    assert($('chat-memory').textContent === '1.0 GiB RAM' && $('performance-cpu').textContent === '0.0 %', 'real zero CPU differs from unknown');
    state = {...savedState, resources:{scope:'geistd', rss_bytes:null, cpu_percent:null}}; renderPerformance();
    assert($('chat-memory').textContent === '— RAM' && $('performance-cpu').textContent === '—', 'unknown resource counters are not zero');
    state = {...savedState, hardware:{...savedState.hardware, known:false, ram:0}}; renderPerformance();
    assert($('performance-ram').textContent === '—', 'failed system memory read is unknown, not zero');
    state = {...savedState, active:'another model'}; renderPerformance();
    assert(lastReply === null && $('performance-tokens').textContent === '—', 'model change invalidates last reply metrics');
    state = savedState; lastReply = measuredReply; renderPerformance();
    input('Which word?'); key(); await tick();
    assert(calls[1].messages.length === 3 && calls[1].messages[1].content === conversation[1].content, 'follow-up includes history without truncation');
    emit({response:'Lighthouse.'}); finish(true); await idle();
    assert($('result').querySelectorAll('article').length === 4 && $ ('result').querySelector('.assistant .markdown').markdownSource === answer+'\nLast line.', 'earlier messages retained');
    assert($('result').textContent.includes(t('Continue response')), 'token limit has explicit continuation');
    input('Draft to keep during continuation');
    const more = [...$('result').querySelectorAll('button')].find(button => button.dataset.label === 'Continue response');
    more.click(); await tick();
    assert($('prompt').value === 'Draft to keep during continuation', 'continuation preserves the next draft');
    emit({response:'More detail.'}); finish(false); await idle();
    fail = true; input('Follow-up that does not fit'); key(); await idle();
    assert(conversation.length === 6 && $('prompt').value === 'Follow-up that does not fit', 'rejected request retains draft and previous context');
    assert($('result').textContent.includes(t('This conversation does not fit the model’s context. Shorten your draft or start a new chat. No earlier messages have been removed.')), 'context limit explained');
    fail = false; input('A response to stop'); key(); await tick(); emit({response:'Partial response'}); await tick(); $('stop').click(); await idle();
    assert(conversation.at(-1).content === 'Partial response' && $('result').textContent.includes(t('Stopped. Partial output is kept here.')), 'stop preserves marked partial response');
    assert(document.activeElement === $('prompt'), 'stopping returns focus to composer');
    assert(lastReply === null && $('chat-speed').textContent === rateText(null), 'aborted reply never reports final generation speed');
    window.confirm = () => false; $('new-chat').click(); assert(conversation.length === 8, 'cancel new chat keeps text');
    window.confirm = () => true; $('new-chat').click(); assert(conversation.length === 0 && !$('chat-empty').hidden && !$('prompt').value, 'new chat clears only this session');
    $('chat-help').open = true;
    const help = document.querySelector('.help-content').getBoundingClientRect();
    assert(help.top >= 0 && help.bottom <= innerHeight && help.left >= 0 && help.right <= innerWidth, 'help readable inside window');
    document.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape', bubbles:true, cancelable:true}));
    assert(!$('chat-help').open && document.activeElement === $('chat-help').querySelector('summary'), 'Escape closes help and returns focus');
    $('chat-help').open = true;
    $('prompt').dispatchEvent(new Event('pointerdown', {bubbles:true}));
    assert(!$('chat-help').open, 'outside click dismisses help');
    $('performance').open = true; await tick();
    const panel = document.querySelector('.performance-content').getBoundingClientRect();
    assert(panel.top >= 0 && panel.bottom <= innerHeight && panel.left >= 0 && panel.right <= innerWidth, 'performance panel stays inside small and zoomed windows');
    assert($('performance').getBoundingClientRect().bottom <= innerHeight && document.documentElement.scrollWidth <= innerWidth, 'compact metrics remain visible without horizontal clipping');
    $('chat-help').open = true; await tick();
    assert(!$('performance').open, 'only one disclosure is open');
    $('performance').open = true; await tick();
    assert(!$('chat-help').open, 'performance closes tips');
    document.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape', bubbles:true, cancelable:true}));
    assert(!$('performance').open && document.activeElement === $('performance').querySelector('summary'), 'performance Escape returns focus');
    $('prompt').focus();
    const computed = getComputedStyle(document.body);
    assert(computed.backgroundColor === 'rgb(250, 248, 242)', 'cream background is consistent across system appearances');
    window.chatChecksDone = true;
  } catch (error) { window.chatChecksError = error.message; }
  finally { api = originalAPI; window.confirm = originalConfirm; }
})();
true;
