#!/bin/sh
# bump-tap.sh <vX.Y.Z> [tap-checkout] — write Formula/geist-serve.rb for
# that release into the geisten/homebrew-tap checkout (cloned to a temp dir
# when not given) and commit. The caller pushes (release.yml does, with the
# TAP_DEPLOY_KEY secret; by hand: sh scripts/bump-tap.sh v0.1.0 && push).
set -eu
TAG=${1:?usage: bump-tap.sh vX.Y.Z [tap-dir]}
VERSION=${TAG#v}
BASE="https://github.com/geisten/geist-serve/releases/download/$TAG"
TAP=${2:-}
if [ -z "$TAP" ]; then
    TAP=$(mktemp -d)/homebrew-tap
    git clone -q "https://github.com/geisten/homebrew-tap" "$TAP"
fi

SUMS=$(curl -fsSL --max-time 60 --retry 3 "$BASE/SHA256SUMS")
sha() { echo "$SUMS" | grep " $1\$" | cut -d' ' -f1; }
MAC=$(sha geist-serve-macos-arm64); LX=$(sha geist-serve-linux-x86_64); LA=$(sha geist-serve-linux-aarch64)
[ -n "$MAC" ] && [ -n "$LX" ] && [ -n "$LA" ] || { echo "bump-tap: SHA256SUMS of $TAG incomplete" >&2; exit 1; }
# geistd ships next to geist-serve from v0.2 on; older tags have no such asset.
DMAC=$(sha geist-serve-macos-arm64-geistd); DLX=$(sha geist-serve-linux-x86_64-geistd); DLA=$(sha geist-serve-linux-aarch64-geistd)
res() { [ -n "$2" ] && printf '      resource "geistd" do\n        url "%s/%s-geistd"\n        sha256 "%s"\n      end\n' "$BASE" "$1" "$2"; }

mkdir -p "$TAP/Formula"
cat > "$TAP/Formula/geist-serve.rb" <<RB
# Generated by geisten/geist-serve scripts/bump-tap.sh — do not edit here.
class GeistServe < Formula
  desc "One local GGUF model behind the Ollama and OpenAI APIs (geist engine)"
  homepage "https://github.com/geisten/geist-serve"
  version "$VERSION"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$BASE/geist-serve-macos-arm64"
      sha256 "$MAC"
$(res geist-serve-macos-arm64 "$DMAC")    end
  end
  on_linux do
    on_intel do
      url "$BASE/geist-serve-linux-x86_64"
      sha256 "$LX"
$(res geist-serve-linux-x86_64 "$DLX")    end
    on_arm do
      url "$BASE/geist-serve-linux-aarch64"
      sha256 "$LA"
$(res geist-serve-linux-aarch64 "$DLA")    end
  end

  def install
    bin.install Dir["geist-serve-*"].reject { |f| f.end_with?("-geistd") }.first => "geist-serve"
    resource("geistd").stage { bin.install Dir["geist-serve-*-geistd"].first => "geistd" } if resources.any? { |r| r.name == "geistd" }
    # brew services runs this wrapper: it reads the model path (and optional
    # flags on a second line) from etc/geist-serve/model, the one file a
    # user edits. Same idea as /etc/default/geist-serve under systemd.
    (bin/"geist-serve-service").write <<~SH
      #!/bin/sh
      conf="#{etc}/geist-serve/model"
      [ -s "\$conf" ] || { echo "geist-serve: put the GGUF path into \$conf (see brew info geist-serve)" >&2; exit 78; }
      model=\$(sed -n 1p "\$conf"); flags=\$(sed -n 2p "\$conf")
      exec "#{opt_bin}/geist-serve" "\$model" \$flags
    SH
    (etc/"geist-serve").mkpath
  end

  service do
    run [opt_bin/"geist-serve-service"]
    keep_alive true
    log_path var/"log/geist-serve.log"
    error_log_path var/"log/geist-serve.log"
    environment_variables OMP_WAIT_POLICY: "active"
  end

  def caveats
    <<~EOS
      Tell the service which model to serve (first line: GGUF path, optional
      second line: flags such as --host 0.0.0.0), then start it:
        echo /path/to/model.gguf > #{etc}/geist-serve/model
        brew services start geist-serve
        curl http://127.0.0.1:11434/api/tags
      Without the service: geist-serve /path/to/model.gguf
    EOS
  end

  test do
    assert_match "usage", shell_output("#{bin}/geist-serve 2>&1", 2)
  end
end
RB
cd "$TAP" && git add Formula/geist-serve.rb && git -c user.name=geist-serve-release -c user.email=noreply@geisten.com commit -q -m "geist-serve $VERSION" && echo "committed in $TAP"
