#!/usr/bin/env python3
"""Generate the API catalog and C policy from one reviewed, versioned source."""
import json
import sys
from pathlib import Path
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root/'quality'))
from evidence import load_bundle
catalog = json.loads((root/'tasks/catalog.json').read_text())
registry = json.loads((root/'quality/registry.json').read_text())
assert registry['schema'] == 1
records = []
record_keys = set()
for bundle in registry['bundles']:
    run, cells = load_bundle(root / bundle)
    for cell in cells:
        key = (run['model_sha256'], run['device'], cell['task'], cell['language'])
        assert key not in record_keys, 'Multiple active evidence bundles for one quality cell'
        record_keys.add(key)
        records.append({**cell, 'model_sha256':run['model_sha256'], 'device':run['device'],
                        'task_version':run['task_versions'][cell['task']], 'bundle':bundle})
catalog['quality_records'] = records
assert catalog['schema'] == 1
seen = set()
rows = []
for t in catalog['tasks']:
    assert t['id'] not in seen and t['id'].isascii()
    seen.add(t['id'])
    assert t['quality'] == 'unverified', 'Verified advice requires per-model evaluation artifacts first'
    assert 0 <= t['input_limit'] <= 12000 and 0 <= t['output_limit'] <= 256
    fields = [json.dumps(t[k]) for k in ('id','version','title','instruction','url')]
    rows.append('{' + ','.join(fields + [str(t['input_limit']),str(t['output_limit'])]) + '}')
output = '/* Generated by embed-tasks.py; edit tasks/catalog.json. */\n'
output += 'static const struct app_task task_registry[] = {\n' + ',\n'.join(rows) + '\n};\n'
output += 'static const char task_catalog[] = ' + json.dumps(json.dumps(catalog,separators=(',',':'))) + ';\n'
output += 'static const struct app_quality_record quality_registry[] = {\n'
for r in records:
    fields = [json.dumps(r[k]) for k in ('model_sha256','task','task_version','language','device')]
    status = {'passed':'APP_QUALITY_PASSED','failed':'APP_QUALITY_FAILED','unverified':'APP_QUALITY_UNVERIFIED'}[r['quality']]
    output += '{' + ','.join(fields+[status]) + '},\n'
output += '{nullptr,nullptr,nullptr,nullptr,nullptr,APP_QUALITY_UNVERIFIED}};\n'
(root/'build').mkdir(exist_ok=True)
(root/'build/app_tasks.h').write_text(output)
