#!/usr/bin/env python3
"""Generate the API catalog and C policy from one reviewed, versioned source."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
catalog = json.loads((root/'tasks/catalog.json').read_text())
assert catalog['schema'] == 1
seen = set()
rows = []
for t in catalog['tasks']:
    assert t['id'] not in seen and t['id'].isascii()
    seen.add(t['id'])
    assert t['quality'] == 'unverified', 'Verified advice requires per-model evaluation artifacts first'
    assert 0 <= t['input_limit'] <= 12000 and 0 <= t['output_limit'] <= 256
    fields = [json.dumps(t[k]) for k in ('id','version','title','instruction','url')]
    rows.append('{' + ','.join(fields + [str(t['input_limit']),str(t['output_limit'])]) + '}')
output = '/* Generated by embed-tasks.py; edit tasks/catalog.json. */\n'
output += 'static const struct app_task task_registry[] = {\n' + ',\n'.join(rows) + '\n};\n'
output += 'static const char task_catalog[] = ' + json.dumps(json.dumps(catalog,separators=(',',':'))) + ';\n'
(root/'build').mkdir(exist_ok=True)
(root/'build/app_tasks.h').write_text(output)
